# Generated by Django 4.2.18 on 2025-01-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_student_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="file",
        ),
        migrations.RemoveField(
            model_name="student",
            name="image",
        ),
    ]
