# Generated by Django 4.2.18 on 2025-01-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0002_receipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="receipe_view_count",
            field=models.IntegerField(default=1),
        ),
    ]
